services:
  db:
    build: ./db
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  db_test:
    build: ./test_db
    ports:
      - "${DB_TEST_EXTERNAL_PORT}:5432"
    profiles:
      - test

  api:
    build: ./api
    ports:
      - "${API_EXTERNAL_PORT}:8000"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_EXTERNAL_PORT}:80"
    env_file:
      - .env

volumes:
  db_data: